# https://github.com/KnpLabs/geekweek12/wiki/Routing

app_home_page:
    pattern: /
    defaults: { _controller: FrameworkBundle:Template:template, template: 'App::homepage.html.twig' }

App:Contacts: ~
